---
title: "In-Season Value"
author: "Brandon"
date: "9/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
#loading packages
for (pkg in c("tidyverse", "tidytext", "reshape2", "plotly", "dplyr", "RecordLinkage",
              "ggplot2")) {library(pkg, character.only = TRUE)}
# pulling the data 
raw_data <- read_csv("/Users/Brandon/Documents/fantasy-football/data/Fantrax-Players-NFL Sim Dynasty .csv") 
sim_contracts <- read_csv("/Users/Brandon/Documents/fantasy-football/data/nflsim-contracts.csv") %>% 
  mutate(name = tolower(name),
         name = trimws(name, which = "both"),
         y2020 = as.integer(y2020),
         y2021 = as.integer(y2021),
         y2022 = as.integer(y2022),
         y2023 = as.integer(y2023),
         y2024 = as.integer(y2024),
         y2025 = as.integer(y2025)) %>% 
  rename(player = name) %>% 
  select(-sim_team)

cleaned_data <- raw_data %>% 
  mutate(Player = trimws(Player, which = "both"),
         Player = tolower(Player)) %>% 
  rename(player = Player, 
         sim_team = Status,
         fppg = `FP/G`, 
         position = Position,
         irl_team = Team,
         age = Age, 
         bye = Bye)

cleaned_data <- cleaned_data %>% 
  full_join(sim_contracts, by = "player") %>% 
  mutate(y2020_value = round(fppg/y2020 * 1000000, 4))
```

```{r, fig.width=8}
eligible_players <- cleaned_data %>% filter(sim_team != "FA" & sim_team != "W (Wed)" & irl_team != "(N/A)") 
# top offensive players for each team 
top_QBs <- eligible_players %>% group_by(sim_team) %>% filter(position == "QB") %>% 
  top_n(1, FPts) %>% top_n(1, bye) %>% filter(FPts != 0)
top_RBs <- eligible_players %>% group_by(sim_team) %>% filter(position == "RB") %>% 
  top_n(2, FPts) %>% top_n(2, bye) %>% filter(FPts != 0)
top_WRs <- eligible_players %>% group_by(sim_team) %>% filter(position == "WR") %>% 
  top_n(2, FPts) %>% top_n(2, bye) %>% filter(FPts != 0)
top_TEs <- eligible_players %>% group_by(sim_team) %>% filter(position == "TE") %>% 
  top_n(1, FPts) %>% top_n(1, bye) %>% filter(FPts != 0)
top_offense <- rbind(top_QBs, top_RBs, top_WRs, top_TEs)
top_players <- paste(c("\\b(?i)(zq3", na.omit(top_offense$player), "zq3)\\b"), collapse = "|")
top_off_flex <- eligible_players %>% 
  group_by(sim_team) %>% 
  filter(!grepl(top_players, player)) %>% 
  filter(position == "RB" | position == "WR" | position == "TE") %>% 
  top_n(1, fppg) %>% top_n(1, bye) %>% filter(FPts != 0)
top_K <- eligible_players %>% group_by(sim_team) %>% filter(position == "K") %>% top_n(1, FPts) %>% filter(FPts != 0)
top_offense <- rbind(top_offense, top_off_flex, top_K)
# top defensive players for each team 
top_DEs <- eligible_players %>% group_by(sim_team) %>% filter(position == "DE") %>% 
  top_n(2, FPts) %>% top_n(2, bye) %>% filter(FPts != 0)
top_DTs <- eligible_players %>% group_by(sim_team) %>% filter(position == "DT") %>% 
  top_n(1, FPts) %>% top_n(1, bye) %>% filter(FPts != 0)
top_LBs <- eligible_players %>% group_by(sim_team) %>% filter(position == "LB") %>% 
  top_n(3, FPts) %>% top_n(3, bye) %>% filter(FPts != 0)
top_CBs <- eligible_players %>% group_by(sim_team) %>% filter(position == "CB") %>% 
  top_n(2, FPts) %>% top_n(2, bye) %>% filter(FPts != 0)
top_Ss <- eligible_players %>% group_by(sim_team) %>% filter(position == "S") %>% 
  top_n(2, FPts) %>% top_n(2, bye) %>% filter(FPts != 0)
top_defense <- rbind(top_DEs, top_DTs, top_LBs, top_CBs, top_Ss)
top_players <- paste(c("\\b(?i)(zq3", na.omit(top_defense$player), "zq3)\\b"), collapse = "|")
top_def_flex <- eligible_players %>% 
  group_by(sim_team) %>% 
  filter(!grepl(top_players, player)) %>% 
  filter(position == "DE" | position == "DT" | position == "LB" | position == "CB" | position == "S") %>% 
  top_n(1, fppg) %>% top_n(1, bye) %>% filter(FPts != 0)
top_defense <- rbind(top_defense, top_def_flex)
top_lineups <- rbind(top_offense, top_defense)
top_lineups %>% filter(sim_team == "JAX")
rm(top_QBs, top_RBs, top_WRs, top_TEs, top_K, top_off_flex, top_players, 
   top_DEs, top_DTs, top_LBs, top_CBs, top_Ss, top_defense, top_def_flex)
```
```{r, fig.height=3, fig.width=8}
top_lineups %>% 
  group_by(sim_team) %>% 
  summarize(total = sum(fppg)) %>% 
  arrange(-total) %>% 
  ggplot(aes(x= reorder(sim_team, -total), y=total)) +
  geom_bar(colour="black", fill="white", stat="identity",
           width = 0.7, position = position_dodge(width=0.7)) +
  theme_minimal() +
  theme(text = element_text(size=15), axis.title.x = element_blank())
```
```{r, fig.height=3, fig.width=8}
team_totals_all <- cleaned_data %>% 
  filter(sim_team != "FA" & sim_team != "W (Wed)" & irl_team != "(N/A)") %>% 
  group_by(sim_team) %>% summarize(all_points = sum(fppg)) 
ideal_lineup <- top_lineups %>% group_by(sim_team) %>% summarize(ideal_lineup = sum(fppg))
left_on_bench <- ideal_lineup %>% 
  full_join(team_totals_all, by = "sim_team") %>% 
  mutate(left_on_bench = all_points - ideal_lineup) %>% 
  arrange(-left_on_bench); left_on_bench; rm(team_totals_all, ideal_lineup)
left_on_bench %>% 
  ggplot(aes(x= reorder(sim_team, -left_on_bench), y=left_on_bench)) +
  geom_bar(colour="black", fill="white", stat="identity",
           width = 0.7, position = position_dodge(width=0.7)) +
  theme_minimal() +
  theme(text = element_text(size=15), axis.title.x = element_blank())
```
```{r, fig.height=3, fig.width=8}
team_value <- cleaned_data %>% 
  filter(sim_team != "FA" & sim_team != "W (Wed)") %>%
  drop_na(y2020_value) %>% 
  group_by(sim_team) %>% 
  summarize(team_value = sum(y2020_value)) %>% 
  arrange(-team_value); team_value
team_value %>% 
  ggplot(aes(x= reorder(sim_team, -team_value), y=team_value)) +
  geom_bar(colour="black", fill="white", stat="identity",
           width = 0.7, position = position_dodge(width=0.7)) +
  theme_minimal() +
  theme(text = element_text(size=15), axis.title.x = element_blank())
```
```{r, fig.height=3, fig.width=8}
value <- cleaned_data %>% select(y2020_value) %>% drop_na(y2020_value) %>% arrange(-y2020_value)
mean(value$y2020_value)
cleaned_data %>% 
  select(player, sim_team, position, age, fppg, bye, y2020, y2020_value) %>%
  arrange(-y2020_value)
```
```{r, fig.height=3, fig.width=8}
cleaned_data %>% 
  select(player, sim_team, position, age, fppg, bye, y2020_value, y2020, y2021) %>%
  filter(sim_team == "NE") %>% 
  arrange(-y2020_value)
```
```{r value_among_tanking_teams}
tanking_teams <- "WAS|GBP|MIN|SF|DET|SEA|NOLA|NE"

cleaned_data %>% 
  filter(grepl(tanking_teams, sim_team) & 
         position == "RB" & # position filter 
         fppg > 3         # points filter
         #age > 23           # age filter
         ) %>% 
  select(player, sim_team, position, age, fppg, bye, y2020, y2020_value, y2021, y2022) %>% 
  arrange(-y2020_value)
```

```{r value_among_statistically_worst_teams}
worst_teams <- cleaned_data %>% 
  filter(sim_team != "FA" & sim_team != "W (Wed)" & irl_team != "(N/A)") %>% 
  group_by(sim_team) %>% 
  summarize(total = sum(fppg)) %>% 
  arrange(-total) %>% 
  filter(total < mean(total))
worst_teams <- paste(c("\\b(?i)(zq3", na.omit(worst_teams$sim_team), "zq3)\\b"), collapse = "|")

cleaned_data %>% 
  filter(grepl(worst_teams, sim_team) & 
         #position == "LB" & # position filter 
         fppg > 8 &         # points filter
         age > 23          # age filter
         & is.na(y2021)
         ) %>% 
  select(player, sim_team, irl_team, position, age, fppg, bye, y2020, y2020_value, y2021) %>% 
  arrange(-y2020_value)
```







